### ISSUE TITLE
运行脚本添加app 总是显示“这不是一个有效链接”如何解决？

### ISSUE THREAD

**Issue by yongjian-dev** [SiriYXR/AppWishList#1]
运行脚本添加app 总是显示“这不是一个有效链接”如何解决？

**Comment by SiriYXR** [comment]
之前的网页解析代码写的有点垃圾，健壮性不是很强，对于一些代码结构略有不同的应用主页会解析失败。要修复这个问题的话需要重写 /tools/GetJson.py 这个代码

**Comment by yongjian-dev** [comment]
如何重写？

**Comment by SiriYXR** [comment]
里面的判断逻辑都要修改，建议使用beautifulsoup来写，你慢慢研究吧。我暂时已经不打算再维护这个项目了。
